tuple1=(1,"a",True)
print(tuple1)
tupleint=(1,5,3,6,3)
print(tupleint)
newtuple=tupleint+(9,)
print(newtuple)
#Tuples are immutable,thats why we did concatenation
print(tupleint.count(3))
newint=(3,4,6,2,7,8,0)
print(newint[1:6])